#!/bin/sh
CONFIG=$1/.config

mkdir	-p	${1}/user
cd	${1}

get_repo ()
{
	git clone	https://www.github.com/emagii/autotooler.git	"$1"
}


add_config_string ()
{
	printf	"CONFIG_%s=\"%s\"\n"	"$1" "$2"	>>	${CONFIG}
}

add_config_yes ()
{
	printf	"CONFIG_%s=y\n"	"$1"			>>	${CONFIG}
}

raw ()
{
	echo	"$1"	>>	${CONFIG}
}

get_repo	"$1"
rsync	-av	"$1/user/"	user
ln	-sf	"../../user"	"$1/src/user"
		
raw						"HAVE_DOT_CONFIG=y"
add_config_string	PROJECT			"$1"
add_config_string	SRC_URI_HOST		"https://www.github.com/emagii"
add_config_string	SRC_URI_REPO		""
add_config_string	WORKDIR			"\${HOME}/projects/autotooler"
add_config_string	PROJECT_TYPE		"library"
add_config_yes		SHARED_LIB	
add_config_yes		LIBRARY

add_config_string	LIBRARY_NAME		"$1"
add_config_string	LIBRARY_VERSION		"1.0"
add_config_string	COPYRIGHT_DATE		"2017"
add_config_string	AUTHOR			"Ulf Samuelsson"
add_config_string	AUTHOR_EMAIL		"ulf@emagii.com"
add_config_string	HOMEPAGE		"http://www.emagii.com/"
add_config_string	AC_PRERQ		"2.59"
add_config_string	AC_CONFIG_HEADER	"src/include/config.h"
add_config_string	AC_CONFIG_MACRO_DIR	"m4"
add_config_string	AM_INIT_AUTOMAKE	"1.10 -Wall no-define"
add_config_string	SRCDIR			"src"

add_config_yes		OS_LINUX
mkdir	-p		$1/m4
